groupme_url = 'https://api.groupme.com/v3/bots/post'
giphy_url = f'http://api.giphy.com/v1/gifs/search?api_key='
zenquotes_url = 'https://zenquotes.io/api/random'
dad_jokes_url = 'https://icanhazdadjoke.com/slack'
chuck_norris_url = 'https://api.chucknorris.io/jokes/random'
nba_url = 'https://site.web.api.espn.com/apis/v2/scoreboard/header?sport=basketball&league=nba'
nfl_url = 'https://site.web.api.espn.com/apis/v2/scoreboard/header?sport=football&league=nfl'